### ISSUE TITLE
function result not initialized to default value

### ISSUE THREAD

**Issue by riwu** [SRL/PascalScript#2]
```
function ResultNot0: integer;
begin
  writeln(result);
end;

var
  x: integer;
begin
  x:= 123;
  x:= ResultNot0;
end.  
```

output is 123. 
Why did the function take x as its initialization value?

**Comment by JohnPeel** [comment]
riwu, You're a little late with this... https://villavu.com/forum/showthread.php?t=56556

**Comment by riwu** [comment]
Apparently this behavior happens in FPC/Delphi too; the variable to be assigned is treated as an implicit var parameter of the function (for optimization purposes). 
Had the misfortune of experiencing this 'feature' when i assumed that a result array was initially empty...
